GET http://localhost:3001/api/blogs
Content-Type: application/json

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNoaXBweURhbiIsImlkIjoiNjA5YThjMTI4ODA0OTUwNzgyMmI5OTBkIiwiaWF0IjoxNjIwNzQxMTQ3fQ.ckt24lz8vTiwr45xpz-zi8oldFJWBVht8jcWiQ8W6Ok

 {
    "title": "Chip Daniels World",
    "author": "CD",
    "url": "chipdaniels.com",
    "likes": 666}
###

DELETE http://localhost:3001/api/blogs/609a530093c9b4045d85835b
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoaW5hZGRkZGRCbGV3IiwiaWQiOiI2MDlhNTM5MTkzYzliNDA0NWQ4NTgzNWUiLCJpYXQiOjE2MjA3MjY3Mjl9.mRpo-lGXdrhirKUgq02MukOLtQPHtBa0JtjFyg5AnbM

 
###
PUT http://localhost:3001/api/blogs/609a2ec38acec5fe65159938
Content-Type: application/json

 {"title": "weener",
    "author": "bob",
    "url": "sex.com",
    "likes": 3333}

###    
POST http://localhost:3001/api/users
Content-Type: application/json

 {"name": "Chip Danies",
 "username": "ChippyDan",
 "password": "ddddd"}


###
POST http://localhost:3003/api/login
Content-Type: application/json

 {"username": "killa",
 "password": "sandwich"}

###
POST http://localhost:3003/api/testing/reset
Content-Type: application/json



 

